export const WEATHER_CONST_STRING = {
  WEATHER_REQUEST_ACTION_CONST_STRING: 'WEATHER_REQUEST_ACTION_CONST_STRING',
  WEATHER_SUCCESS_ACTION_CONST_STRING: 'WEATHER_SUCCESS_ACTION_CONST_STRING',
  WEATHER_FAILURE_ACTION_CONST_STRING: 'WEATHER_FAILURE_ACTION_CONST_STRING',
};
